Repository andela/ah-nyati-backend, pull requests merged in 2019-07, with the labels that each got.

#24 #166841013 User should be able to create profile
  package-lock.json
  package.json
  src/controllers/Auth.js
  src/controllers/socialController.js
  src/controllers/userController.js
  src/db/config/config.js
  src/db/migrations/20190701212849-create-blacklist.js
  src/db/models/blacklist.js
  src/helpers/profilePic.js
  src/helpers/verifyToken.js
  src/middleware/Auth.js
  src/middleware/ValidateToken.js
  src/middleware/validators/errorMessages.js
  src/middleware/validators/profileValidator.js
  src/routes/index.js
  src/routes/userRoute.js
  src/server.js
  test/img/test.png
  test/img/test.srt
  test/user.test.js
Labels: reviewed!!!

#34 #166841006 user signup endpoint
  .env.sample
  .travis.yml
  README.md
  package-lock.json
  package.json
  src/controllers/Auth.js
  src/controllers/socialController.js
  src/db/config/config.js
  src/db/migrations/20190709090055-create-like.js
  src/db/migrations/20190709125502-create-tag.js
  src/db/models/article.js
  src/db/models/like.js
  src/db/models/tag.js
  src/db/models/user.js
  src/helpers/helpers.js
  src/helpers/mail/mailTemplate/signupEmailTemplate.js
  src/helpers/mail/mailer.js
  src/routes/auth.js
  test/auth.test.js
Labels: reviewed!!!

#27 #166841007 User signin endpoint
  .env.sample
  package-lock.json
  package.json
  src/controllers/Auth.js
  src/db/config/config.js
  src/db/migrations/30181008085213-create-comment.js
  src/db/migrations/30181008085214-create-rating.js
  src/db/models/comment.js
  src/db/models/rating.js
  src/db/seeders/20190701155734-user.js
  src/helpers/mail/mailer.js
  src/helpers/verifyToken.js
  src/routes/ratingRoute.js
  test/auth.test.js
  test/user.test.js
Labels: rebase required

#32 #166841009 Implement auth validation (AUTH)
  package-lock.json
  src/controllers/Auth.js
  src/db/migrations/20190707105525-create-follow.js
  src/db/models/article.js
  src/middleware/authValidator.js
  src/middleware/checkDuplicate.js
  src/middleware/validate.js
  src/routes/auth.js
  test/auth.test.js
  test/authValidator.test.js
Labels: reviewed!!!

#30 167119509 hound bug fix
  .eslintignore
  .eslintrc
  .hound.yml
  .prettierrc
  package-lock.json
  package.json
  src/db/migrations/20190701154222-create-user.js
  src/db/migrations/20190701162137-create-category.js
  src/db/migrations/20190701163716-create-article.js
  src/db/migrations/20190701212849-create-blacklist.js
  src/db/migrations/20190709090055-create-like.js
  src/db/migrations/20190709125502-create-tag.js
  src/db/migrations/30181008085214-create-rating.js
  src/db/models/article.js
  src/db/models/category.js
  src/db/models/index.js
  src/db/models/user.js
  src/db/seeders/20190701162733-category.js
  src/db/seeders/20190701174210-article.js
  src/middleware/Auth.js
  src/server.js
  test/index.test.js
Labels: teammate's review

#28 #167116306 fix swagger documentation bug
  src/db/migrations/20190701154222-create-user.js
  src/routes/auth.js
  src/server.js
  swagger.js
  test/index.test.js
Labels: teammate's review

#29 #166841021 User should be able to follow and unfollow each other
  src/controllers/userController.js
  src/db/migrations/20190707105525-create-follow.js
  src/db/models/article.js
  src/db/models/follow.js
  src/db/models/user.js
  src/db/seeders/20190701155734-user.js
  src/helpers/findItem.js
  src/middleware/Auth.js
  src/routes/index.js
  src/routes/userRoute.js
  test/auth.test.js
  test/follow.test.js
  test/user.test.js
Labels: reviewed!!!

#35 #166841026 add search functionality feature
  src/controllers/articleController.js
  src/db/migrations/20190701154222-create-user.js
  src/db/migrations/20190701163716-create-article.js
  src/db/models/article.js
  src/db/seeders/20190709125947-tag.js
  src/helpers/searchHelper.js
  src/middleware/searchInputValidator.js
  src/routes/articleRoute.js
  src/routes/index.js
  test/searchFilter.test.js
Labels: reviewed!!!

#33 #166841011 User should be able to reset password
  package-lock.json
  src/controllers/Auth.js
  src/db/config/config.js
  src/helpers/findItem.js
  src/helpers/mail/mailTemplate/passwordResetTemplate.js
  src/middleware/tokenGenerator.js
  src/routes/auth.js
  test/passwordreset.test.js
Labels: reviewed!!!
